name = "cloud-disk"
main = "src/index.ts"
compatibility_date = "2025-06-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./public"
binding = "ASSETS"

# 一键部署时会自动创建并绑定
[[d1_databases]]
binding = "DB"
database_name = "cloud-disk"
migrations_dir = "migrations"

# 一键部署时在配置页将 KV 命名空间名称设为 cloud-disk（与 D1 同名，类型不同不冲突）
[[kv_namespaces]]
binding = "KV"

# R2 须与 KV 区分命名
[[r2_buckets]]
binding = "R2"
bucket_name = "cloud-disk-files"

[vars]
APP_NAME = "CloudDisk"
